### ISSUE TITLE
Timeout when fetching @my_deps

### ISSUE THREAD

**Issue by milan-tom** [Xcov19/covidX#108]
**Describe the bug**
After running `docker-compose up --build`, a timeout occurs when fetching `@my_deps`.

**To Reproduce**
1. Clone the repository
2. Add a `.env` file in the cloned repository.
3. Run `docker-compose up --build` 
4. Wait for building to reach stage of timing out while fetching `@my_deps`
5. See error

**Expected behavior**
`@my_deps` fetched successfully without timeout

**Desktop:**
 - OS: Ubuntu 20.04.2.0 LTS

**Comment by codecakes** [comment]
Solution is to increase the TIMEOUT not this: https://github.com/Xcov19/covidX/pull/109

**Comment by milan-tom** [comment]
New error message:
```
(16:34:56) ERROR: An error occurred during the fetch of repository 'my_deps':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6666cd76f96956469e7be39d750cc7d9/external/rules_python/python/pip.bzl", line 49, column 13, in _pip_import_impl
                fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Timed out)
(16:34:56) Loading: 0 packages loaded
(16:34:56) ERROR: Error fetching repository: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6666cd76f96956469e7be39d750cc7d9/external/rules_python/python/pip.bzl", line 49, column 13, in _pip_import_impl
                fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Timed out)
(16:34:56) Loading: 0 packages loaded
(16:34:57) ERROR: no such package '@my_deps//': pip_import failed:  (Timed out)
(16:34:57) Loading: 0 packages loaded
(16:34:57) INFO: Elapsed time: 620.001s
(16:34:57) Loading: 0 packages loaded
(16:34:57) INFO: 0 processes.
(16:34:57) Loading: 0 packages loaded
(16:34:57) FAILED: Build did NOT complete successfully (0 packages loaded)
(16:34:57) FAILED: Build did NOT complete successfully (0 packages loaded)
The command '/bin/sh -c PULLER_TIMEOUT=3600 CPPFLAGS="$(pg_config --cppflags)" LDFLAGS="$(pg_config --ldflags)" bazel build :manage --watchfs --spawn_strategy=standalone --copt --aspects=@bazel_tools//tools/python:srcs_version.bzl%find_requirements --verbose_failures=true --show_timestamps=true --python_version=PY3 --build_python_zip --sandbox_debug --color=yes --curses=yes --jobs=2000 --loading_phase_threads=HOST_CPUS --action_env=LDFLAGS --action_env=CPPFLAGS --action_env=DEBUG_ENV --action_env=SECRET_KEY --action_env=$BAZEL_CACHE --action_env=PULLER_TIMEOUT --disk_cache=$BAZEL_CACHE' returned a non-zero code: 1
ERROR: Service 'backend' failed to build
```

**Comment by milan-tom** [comment]
It always seems to timeout around the 600 seconds mark. I increased the timeout to 9999999, and it is still failing. Thus, it is not an issue of not providing enough time.

**Comment by codecakes** [comment]
This issue is explained, fixed &  verified in  https://github.com/Xcov19/covidX/pull/112 and is now working in develop branch;
Unless you face any issues running the following, I am closing this issue, in which case reopen this but not before trying this:
`docker run --rm -it --security-opt apparmor=unconfined codecakes/covidx_backend`
