### ISSUE TITLE
Error when building with Bazel on linux

### ISSUE THREAD

**Issue by ElijahAhianyo** [Xcov19/covidX#53]
building locally using the command :
```
bazel build :manage --watchfs --spawn_strategy=standalone --copt --aspects=@bazel_tools//tools/python:srcs_version.bzl%find_requirements --verbose_failures=true --show_timestamps=true --python_version=PY3 --build_python_zip --sandbox_debug --color=yes --curses=yes --jobs=20 --loading_phase_threads=HOST_CPUS --action_env=LDFLAGS --action_env=CPPFLAGS --action_env=DEBUG_ENV --action_env=SECRET_KEY
```

resulted in the following error:
```
 File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/src/compile.py", line 7, in <module>
    compile.cli()
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 444, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 169, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 274, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 380, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/local.py", line 74, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 229, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 181, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 313, in _get_abstract_dist_for
    self._populate_link(req)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 279, in _populate_link
    req.link = self.finder.find_requirement(req, upgrade)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/index/package_finder.py", line 930, in find_requirement
    req)
pip._internal.exceptions.DistributionNotFound: No matching distribution found for ipython==7.18.1 (from -r /home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/my_deps/requirements.txt (line 303))
)
(16:23:04) ERROR: no such package '@my_deps//': pip_compile failed:  (/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py:297: FutureWarning: --index and --no-index are deprecated and will be removed in future versions. Use --emit-index-url/--no-emit-index-url instead.
  category=FutureWarning,
  ERROR: Could not find a version that satisfies the requirement ipython==7.18.1 (from -r /home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/my_deps/requirements.txt (line 303)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1)
Traceback (most recent call last):
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/src/compile.py", line 7, in <module>
    compile.cli()
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 444, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 169, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 274, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 380, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/local.py", line 74, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 229, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 181, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 313, in _get_abstract_dist_for
    self._populate_link(req)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 279, in _populate_link
    req.link = self.finder.find_requirement(req, upgrade)
  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/index/package_finder.py", line 930, in find_requirement
    req)
pip._internal.exceptions.DistributionNotFound: No matching distribution found for ipython==7.18.1 (from -r /home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/my_deps/requirements.txt (line 303))
)
(16:23:04) INFO: Elapsed time: 21.606s
(16:23:04) INFO: 0 processes.
(16:23:04) FAILED: Build did NOT complete successfully (0 packages loaded)
```
looks like it couldnt find a suitable version(7.18.1) stated in the specified requirements file. I tried changing the version in the requirement file but that didnt work. 
Im using `python 3.6.9` and bazel verion `bazel 3.7.0`

**Comment by adepeter** [comment]
I think I faced the same issue. Well I didn't use bazel anymore to run the project. In my local, I installed the requirements, and ran basically with Python manage.py runserver.

However I need to draw your attention to the fact that I made some slight changes to the settings.py file. 

My work around was to:

A. DEBUG = True
B. SECRET_KEYS = 'just_type_in_any_random_char_or_use_this'

That was all. 

Then run "python manage.py runserver" but remember you need to create a DB DATA and these data should correspond with what is in settings.py

**Comment by codecakes** [comment]
> I think I faced the same issue. Well I didn't use bazel anymore to run the project. In my local, I installed the requirements, and ran basically with Python manage.py runserver.
> 
> However I need to draw your attention to the fact that I made some slight changes to the settings.py file.
> 
> My work around was to:
> 
> A. DEBUG = True
> B. SECRET_KEY = 'just_type_in_any_random_char_or_use_this'
> 
> That was all.
> 
> Then run "python manage.py runserver" but remember you need to create a DB DATA and these data should correspond with what is in settings.py

Can you share the settings.py changes with @ElijahAhianyo

**Comment by adepeter** [comment]
https://github.com/adepeter/covidX/blob/master/covidX/settings.py

**Comment by codecakes** [comment]
> building locally using the command :
> 
> ```
> bazel build :manage --watchfs --spawn_strategy=standalone --copt --aspects=@bazel_tools//tools/python:srcs_version.bzl%find_requirements --verbose_failures=true --show_timestamps=true --python_version=PY3 --build_python_zip --sandbox_debug --color=yes --curses=yes --jobs=20 --loading_phase_threads=HOST_CPUS --action_env=LDFLAGS --action_env=CPPFLAGS --action_env=DEBUG_ENV --action_env=SECRET_KEY
> ```
> 
> resulted in the following error:
> 
> ```
>  File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/src/compile.py", line 7, in <module>
>     compile.cli()
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/decorators.py", line 21, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 444, in cli
>     results = resolver.resolve(max_rounds=max_rounds)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 169, in resolve
>     has_changed, best_matches = self._resolve_one_round()
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 274, in _resolve_one_round
>     their_constraints.extend(self._iter_dependencies(best_match))
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 380, in _iter_dependencies
>     dependencies = self.repository.get_dependencies(ireq)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/local.py", line 74, in get_dependencies
>     return self.repository.get_dependencies(ireq)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 229, in get_dependencies
>     download_dir, ireq, wheel_cache
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 181, in resolve_reqs
>     results = resolver._resolve_one(reqset, ireq)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
>     abstract_dist = self._get_abstract_dist_for(req_to_install)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 313, in _get_abstract_dist_for
>     self._populate_link(req)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 279, in _populate_link
>     req.link = self.finder.find_requirement(req, upgrade)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/index/package_finder.py", line 930, in find_requirement
>     req)
> pip._internal.exceptions.DistributionNotFound: No matching distribution found for ipython==7.18.1 (from -r /home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/my_deps/requirements.txt (line 303))
> )
> (16:23:04) ERROR: no such package '@my_deps//': pip_compile failed:  (/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py:297: FutureWarning: --index and --no-index are deprecated and will be removed in future versions. Use --emit-index-url/--no-emit-index-url instead.
>   category=FutureWarning,
>   ERROR: Could not find a version that satisfies the requirement ipython==7.18.1 (from -r /home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/my_deps/requirements.txt (line 303)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 6.0.0rc1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.5.0, 7.0.0b1, 7.0.0rc1, 7.0.0, 7.0.1, 7.1.0, 7.1.1, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.6.1, 7.7.0, 7.8.0, 7.9.0, 7.10.0, 7.10.1, 7.10.2, 7.11.0, 7.11.1, 7.12.0, 7.13.0, 7.14.0, 7.15.0, 7.16.0, 7.16.1)
> Traceback (most recent call last):
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/src/compile.py", line 7, in <module>
>     compile.cli()
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/click/decorators.py", line 21, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 444, in cli
>     results = resolver.resolve(max_rounds=max_rounds)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 169, in resolve
>     has_changed, best_matches = self._resolve_one_round()
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 274, in _resolve_one_round
>     their_constraints.extend(self._iter_dependencies(best_match))
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/resolver.py", line 380, in _iter_dependencies
>     dependencies = self.repository.get_dependencies(ireq)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/local.py", line 74, in get_dependencies
>     return self.repository.get_dependencies(ireq)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 229, in get_dependencies
>     download_dir, ireq, wheel_cache
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/piptools/repositories/pypi.py", line 181, in resolve_reqs
>     results = resolver._resolve_one(reqset, ireq)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
>     abstract_dist = self._get_abstract_dist_for(req_to_install)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 313, in _get_abstract_dist_for
>     self._populate_link(req)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/resolution/legacy/resolver.py", line 279, in _populate_link
>     req.link = self.finder.find_requirement(req, upgrade)
>   File "/home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/com_github_ali5h_rules_pip/third_party/py/pip/_internal/index/package_finder.py", line 930, in find_requirement
>     req)
> pip._internal.exceptions.DistributionNotFound: No matching distribution found for ipython==7.18.1 (from -r /home/zeus-of-python/.cache/bazel/_bazel_zeus-of-python/70911cba2b311749b083e2827e4b54a7/external/my_deps/requirements.txt (line 303))
> )
> (16:23:04) INFO: Elapsed time: 21.606s
> (16:23:04) INFO: 0 processes.
> (16:23:04) FAILED: Build did NOT complete successfully (0 packages loaded)
> ```
> 
> looks like it couldnt find a suitable version(7.18.1) stated in the specified requirements file. I tried changing the version in the requirement file but that didnt work.
> Im using `python 3.6.9` and bazel verion `bazel 3.7.0`

@ElijahAhianyo to build locally you must have pip pkgs installed and pip-compile'd first before you run off w/ bazel;
check slack for updates; You don't need to set this up now yourself;

**Comment by codecakes** [comment]
> https://github.com/adepeter/covidX/blob/master/covidX/settings.py

@adepeter 
we don't need to change settings to run an instance. 
try running master first using the approach as i pointed above :point_up:  to @ElijahAhianyo ;
your testing should be run with bazel locally;

**Comment by ElijahAhianyo** [comment]
okay @codecakes i run in to the same issue after following the update command that is running this  
```
CPPFLAGS="$(pg_config --cppflags)" LDFLAGS="$(pg_config --ldflags)" python3 -m pip install -r requirements_dev.txt
```
i did some digging and realized ipython `7.18.1` requires python3.7+ . After updating my python version from `python 3.6.9` to `python 3.8` everything worked!

**Comment by codecakes** [comment]
> okay @codecakes I run into the same issue after following the updated command in the Readme, that is running this
> 
> ```
> CPPFLAGS="$(pg_config --cppflags)" LDFLAGS="$(pg_config --ldflags)" python3 -m pip install -r requirements_dev.txt
> ```
> 
> i did some digging and realized ipython `7.18.1` required python3.7+. After updating my python version from `python 3.6.9` to `python 3.8` everything worked!
> I think it's worth stating the required python version in the Readme

@ElijahAhianyo 
1. please file this as a separate bug issue and provide the resolve there as well; Under [here "Common Issues"](https://github.com/Xcov19/covidX#common-issues) in the readme, add to the list your bug issues as well and send a PR;
2. Check https://xcov19.slack.com/archives/C01B2H0FP0F/p1605960540008600

**Comment by ElijahAhianyo** [comment]
> > okay @codecakes I run into the same issue after following the updated command in the Readme, that is running this
> > ```
> > CPPFLAGS="$(pg_config --cppflags)" LDFLAGS="$(pg_config --ldflags)" python3 -m pip install -r requirements_dev.txt
> > ```
> > 
> > 
> > i did some digging and realized ipython `7.18.1` required python3.7+. After updating my python version from `python 3.6.9` to `python 3.8` everything worked!
> > I think it's worth stating the required python version in the Readme
> 
> @ElijahAhianyo
> 
> 1. please file this as a separate bug issue and provide the resolve there as well; Under [here "Common Issues"](https://github.com/Xcov19/covidX#common-issues) in the readme, add to the list your bug issues as well and send a PR;
> 2. Check https://xcov19.slack.com/archives/C01B2H0FP0F/p1605960540008600

sure. Ill do just that
